// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Glow } from "@/components/ui/glow"; // Adjust path if needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx - UPDATED
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
        {/* Background - use z-0 instead of -z-10 */}
        <div className="fixed inset-0 overflow-hidden z-0">
          <Glow variant="top" className="opacity-20" />
          <Glow variant="center" className="opacity-20" />
          <Glow variant="bottom" className="opacity-20" />
        </div>
        
        {/* Content - higher z-index */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
    </html>
  );
}